
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Casgem_Portfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_projects
{

    public int ProjectID { get; set; }

    public string Name_ { get; set; }

    public string Purpose { get; set; }

    public string Description { get; set; }

    public string ProjectType { get; set; }

}

}
