
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Casgem_Portfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_about
{

    public int AboutID { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Mail { get; set; }

    public string Des { get; set; }

    public string ImageUrl { get; set; }

}

}
