
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Casgem_Portfolio.Models.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TblDepartment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TblDepartment()
    {

        this.Tbl_Employee = new HashSet<Tbl_Employee>();

    }


    public int DepartmentID { get; set; }

    public string DepartmentName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tbl_Employee> Tbl_Employee { get; set; }

}

}
